/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                neutral: {
                    50: '#f8fafc',
                    100: '#f1f5f9',
                    200: '#e2e8f0',
                    300: '#cbd5e1',
                    400: '#94a3b8',
                    500: '#64748b',
                    600: '#475569',
                    700: '#334155',
                    800: '#1e293b',
                    900: '#0f172a',
                    950: '#020617',
                },
                primary: {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                    950: '#172554',
                },
                secondary: {
                    50: '#fdf4ff',
                    100: '#fae8ff',
                    200: '#f5d0fe',
                    300: '#f0abfc',
                    400: '#e879f9',
                    500: '#d946ef',
                    600: '#c026d3',
                    700: '#a21caf',
                    800: '#86198f',
                    900: '#701a75',
                    950: '#4a044e',
                },
                success: {
                    50: '#ecfdf5',
                    500: '#10b981',
                    700: '#047857',
                },
                warning: {
                    50: '#fffbeb',
                    500: '#f59e0b',
                    700: '#b45309',
                },
                error: {
                    50: '#fef2f2',
                    500: '#ef4444',
                    700: '#b91c1c',
                },
                info: {
                    50: '#f0f9ff',
                    500: '#0ea5e9',
                    700: '#0369a1',
                },
                // Futuristic accent colors
                neon: {
                    cyan: '#06b6d4',
                    purple: '#9333ea',
                    green: '#22c55e',
                    amber: '#f59e0b',
                    pink: '#ec4899',
                },
                glass: {
                    light: 'rgba(255,255,255,0.08)',
                    medium: 'rgba(255,255,255,0.12)',
                    dark: 'rgba(0,0,0,0.40)',
                    border: 'rgba(255,255,255,0.10)',
                },
                provider: {
                    blue: {
                        50: '#eff6ff',
                        100: '#dbeafe',
                        200: '#bfdbfe',
                        300: '#93c5fd',
                        400: '#60a5fa',
                        500: '#3b82f6',
                        600: '#2563eb',
                        700: '#1d4ed8',
                        800: '#1e40af',
                        900: '#1e3a8a',
                        950: '#172554',
                    },
                    slate: {
                        50: '#f8fafc',
                        100: '#f1f5f9',
                        200: '#e2e8f0',
                        300: '#cbd5e1',
                        400: '#94a3b8',
                        500: '#64748b',
                        600: '#475569',
                        700: '#334155',
                        800: '#1e293b',
                        900: '#0f172a',
                        950: '#020617',
                    },
                },
                admin: {
                    cyan: '#00ffe7',
                    green: '#00ff8c',
                    amber: '#ffb300',
                    red: '#ff3860',
                    void: '#020408',
                    surface: '#050d14',
                    raised: '#0a1829',
                },
                theme: {
                    bg: 'var(--theme-bg, #ffffff)',
                    primary: 'var(--theme-primary, #3b82f6)',
                    secondary: 'var(--theme-secondary, #8b5cf6)',
                    accent: 'var(--theme-accent, #06b6d4)',
                    navbar: 'var(--theme-navbar, #ffffff)',
                    sidebar: 'var(--theme-sidebar, #f8fafc)',
                    card: 'var(--theme-card-bg, #ffffff)',
                    border: 'var(--theme-border, #e2e8f0)',
                    text: {
                        primary: 'var(--theme-text-primary, #0f172a)',
                        secondary: 'var(--theme-text-secondary, #475569)',
                    },
                    btn: {
                        bg: 'var(--theme-btn-bg, #3b82f6)',
                        text: 'var(--theme-btn-text, #ffffff)',
                    },
                    table: {
                        header: 'var(--theme-table-header, #f1f5f9)',
                        row: 'var(--theme-table-row, #ffffff)',
                    },
                    hover: 'var(--theme-hover, #f8fafc)',
                },
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                heading: ['"Space Grotesk"', 'Inter', 'sans-serif'],
                mono: ['"JetBrains Mono"', 'Menlo', 'monospace'],
            },
            boxShadow: {
                'xs': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
                'soft': '0 4px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px -1px rgba(0, 0, 0, 0.02)',
                'float': '0 10px 15px -3px rgba(0, 0, 0, 0.05), 0 4px 6px -2px rgba(0, 0, 0, 0.025)',
                'glow': '0 0 15px rgba(59, 130, 246, 0.5)',
                'glow-cyan': '0 0 24px rgba(6, 182, 212, 0.4), 0 0 48px rgba(6, 182, 212, 0.15)',
                'glow-purple': '0 0 24px rgba(147, 51, 234, 0.4), 0 0 48px rgba(147, 51, 234, 0.15)',
                'glow-green': '0 0 24px rgba(34, 197, 94, 0.4), 0 0 48px rgba(34, 197, 94, 0.15)',
                'glow-amber': '0 0 24px rgba(245, 158, 11, 0.35), 0 0 48px rgba(245, 158, 11, 0.12)',
                'glow-red': '0 0 24px rgba(239, 68, 68, 0.4), 0 0 48px rgba(239, 68, 68, 0.15)',
                'glass': '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
                'glass-sm': '0 4px 16px 0 rgba(0, 0, 0, 0.25)',
                'card': '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.04)',
                'card-hover': '0 4px 12px rgba(0,0,0,0.1), 0 2px 6px rgba(0,0,0,0.06)',
            },
            animation: {
                'fade-in': 'fadeIn 0.3s ease-out forwards',
                'slide-up': 'slideUp 0.4s ease-out forwards',
                'slide-down': 'slideDown 0.3s ease-out forwards',
                'slide-in-right': 'slideInRight 0.3s ease-out forwards',
                'scale-in': 'scaleIn 0.2s ease-out forwards',
                'shimmer': 'shimmer 2s linear infinite',
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'bounce-slow': 'bounce 2s infinite',
                // New futuristic animations
                'glow-pulse': 'glowPulse 2s ease-in-out infinite',
                'orb-spin': 'orbSpin 4s linear infinite',
                'float-up': 'floatUp 3s ease-in-out infinite',
                'neural-scan': 'neuralScan 1.5s ease-in-out infinite',
                'gradient-shift': 'gradientShift 4s ease infinite',
                'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%': { opacity: '0', transform: 'translateY(10px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                slideDown: {
                    '0%': { opacity: '0', transform: 'translateY(-10px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                slideInRight: {
                    '0%': { opacity: '0', transform: 'translateX(20px)' },
                    '100%': { opacity: '1', transform: 'translateX(0)' },
                },
                scaleIn: {
                    '0%': { opacity: '0', transform: 'scale(0.95)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-1000px 0' },
                    '100%': { backgroundPosition: '1000px 0' },
                },
                glowPulse: {
                    '0%, 100%': { opacity: '0.6', transform: 'scale(1)' },
                    '50%': { opacity: '1', transform: 'scale(1.05)' },
                },
                orbSpin: {
                    '0%': { transform: 'rotate(0deg)' },
                    '100%': { transform: 'rotate(360deg)' },
                },
                floatUp: {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-8px)' },
                },
                neuralScan: {
                    '0%': { transform: 'translateY(-100%)' },
                    '100%': { transform: 'translateY(100%)' },
                },
                gradientShift: {
                    '0%, 100%': { backgroundPosition: '0% 50%' },
                    '50%': { backgroundPosition: '100% 50%' },
                },
            },
            transitionTimingFunction: {
                'ease-smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
                'ease-bounce': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
            },
            backdropBlur: {
                xs: '2px',
                glass: '14px',
                heavy: '24px',
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
                'mesh-cyan-purple': 'linear-gradient(135deg, #020617 0%, #0a0f2e 40%, #0d1117 100%)',
                'glass-shimmer': 'linear-gradient(90deg, transparent, rgba(255,255,255,0.08), transparent)',
            },
        },
    },
    plugins: [],
}
